#!/bin/bash
# bash script for resetting and flashing rp2040/pico autonomously
# argument 1 is serial port which pico is connected to

DEV="/dev/ttyACM0"


function wait_for_serial() {
	# wait for serial device to mount	
	echo waiting for pico to mount
	count=0
	while [ ! -e $DEV ]
	do 
		sleep 0.5
		count=$((count+1))
		echo .
		# exit script if no serial device could be found
		if [ $count -ge 30 ]
		then 
			echo No device found on serial port $1 - Aborting process.
			exit
		fi
	done
}

function delete_old_relics() {
	# delete old pico mass storage relics from file system 
	echo deleted mass storage relics \(if existing\): /
	sudo find /media/$USER/ -type d -name 'RPI-RP*' -prune -print -exec rm -rf {} \;
}

function reset_pico() {
	# reset pico over baud rate change to 1200 baud
	echo resetting pico
	sudo stty -F $DEV 1200
}


function wait_for_disk() {
	# wait until pico has mounted as mass storage device
	count=0
	while [ ! -d /media/$USER/RPI-RP2 ]
	do 
		sleep 0.5
		echo .
		count=$((count+1))
		# exit script if pico did not mount as mass storage device
		if [ $count -ge 30 ]; then 
			echo pico did not reboot - try again!
			exit
		fi
	done
	# give pico some time to mount fully
	sleep 2.0
}

function copy_file() {
	# copy flash-file to pico
	echo copy flash-file to pico...
	sudo find -type f -name '*.uf2' -exec cp -prv {} /media/$USER/RPI-RP2 \;

	# check if flash has been successful
	count=0
	while [ -d /media/$USER/RPI-RP2 ]
	do 
		sleep 0.5
		echo .
		count=$((count+1))
		# exit script if flash was not successful (pico is still mounted as mass storage device)
		if [ $count -ge 30 ]; then 
			echo pico was reset but could not be flashed - please drag and drop .uf2-file manually!
			exit
		fi
	done

	echo flash successful - black magic happened ~\\\(o.O~\\\)
}

if [ -z "$( ls -A /dev/serial/by-id/usb-Raspberry_Pi_Pico* )" ]; then
  echo "no RP2040 serial devices => assuming RP2040 already in bootloader"
else
  echo "found RP2040 serial devices => assuming RP2040 not yet in bootloader"
  DEV=/dev/$1
  echo "DEV=$DEV"
  # optional
  #exit
  wait_for_serial
  delete_old_relics
  reset_pico
fi

#exit

# RP2040 is now in bootloader
wait_for_disk
copy_file






